const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs = require('fs');
const crypto = require('crypto');
const path = require('path');
const assert = require('node:assert/strict');

function otp(secret) {
    const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
    let bits = '';
    for (const letter of secret) bits += alphabet.indexOf(letter).toString(2).padStart(5, '0');
    const bytes = [];
    for (let i = 0; i + 8 <= bits.length; i += 8) bytes.push(parseInt(bits.slice(i, i + 8), 2));
    const counter = Buffer.alloc(8);
    counter.writeBigUInt64BE(BigInt(Math.floor(Date.now() / 30000)));
    const digest = crypto.createHmac('sha1', Buffer.from(bytes)).update(counter).digest();
    return ((digest.readUInt32BE(digest[19] & 15) & 0x7fffffff) % 1000000).toString().padStart(6, '0');
}

(async () => {
    const root = process.env.FORM_BROWSER_STORAGE;
    if (!root || !root.includes('forms-browser')) throw Error('Isolated browser storage is required.');
    const fixture = JSON.parse(fs.readFileSync(path.join(root, 'browser-fixtures.json'), 'utf8'));
    const base = process.env.FORM_BROWSER_URL || 'http://127.0.0.1:8023';
    const browser = await chromium.launch({ headless: true, channel: 'msedge' });
    try {
        const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
        const page = await context.newPage();
        const errors = [];
        page.on('pageerror', error => errors.push(error.message));
        await page.goto(base + '/forms/' + fixture.slug);
        await page.getByRole('heading', { name: 'Kenali potensi Anda' }).waitFor();
        await page.screenshot({ path: path.join(root, 'public-desktop.png'), fullPage: true });
        await page.setViewportSize({ width: 390, height: 844 });
        await page.screenshot({ path: path.join(root, 'public-mobile.png'), fullPage: true });
        assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'Public form must fit mobile viewport.');
        await page.goto(base + '/form-access/' + fixture.token);
        await page.getByRole('button', { name: 'Verifikasi & lanjutkan' }).click();
        await page.waitForURL('**/form-responses/*');
        await page.getByLabel('Nama lengkap', { exact: false }).fill('Nadia Amelia');
        await page.getByLabel('Domisili saat ini', { exact: true }).fill('Makassar');
        await page.getByLabel('Tanggal lahir', { exact: true }).fill('1998-05-12');
        await page.getByLabel('Pendidikan terakhir', { exact: true }).selectOption('Sarjana');
        await page.getByRole('button', { name: 'Simpan draf', exact: true }).click();
        await page.getByText('Draf berhasil disimpan. Belum dikirim final.', { exact: true }).waitFor();
        await page.locator('input[type=file]').setInputFiles({ name: 'cv.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4\n1 0 obj\n<< /Type /Catalog >>\nendobj\n%%EOF') });
        await page.getByRole('button', { name: 'Unggah file', exact: true }).click();
        await page.getByText('cv.pdf', { exact: true }).waitFor();
        await page.getByLabel('Saya menyatakan data benar', { exact: false }).check();
        await page.getByRole('button', { name: 'Tinjau & kirim', exact: true }).click();
        await page.getByRole('heading', { name: 'Periksa sebelum dikirim' }).waitFor();
        await page.getByLabel('Data dan dokumen sudah benar.', { exact: false }).check();
        await page.getByRole('button', { name: 'Kirim final', exact: true }).click();
        await page.getByRole('heading', { name: 'Terima kasih, Nadia Amelia' }).waitFor();
        await page.screenshot({ path: path.join(root, 'receipt-mobile.png'), fullPage: true });

        const admin = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
        admin.on('pageerror', error => errors.push(error.message));
        await admin.goto(base + '/admin/login');
        await admin.locator('input[type=email]').fill(fixture.admin);
        await admin.locator('input[type=password]').fill(fixture.password);
        await admin.locator('button[type=submit]').click();
        await admin.locator('input[autocomplete=one-time-code]').fill(otp(fixture.secret));
        await admin.locator('button[type=submit]').click();
        await admin.waitForURL(/\/admin\/recruitment(?:\?|$)/);
        await admin.goto(base + '/admin/candidate-forms');
        await admin.getByRole('button', { name: 'Respons masuk', exact: true }).click();
        await admin.locator('.response-list-panel').waitFor();
        await admin.evaluate(() => window.scrollTo(0, 0));
        await admin.screenshot({ path: path.join(root, 'admin-response-list.png'), fullPage: true });
        await admin.setViewportSize({ width: 390, height: 844 });
        await admin.evaluate(() => window.Alpine.store('sidebar').close());
        await admin.locator('.fi-sidebar-close-overlay').waitFor({ state: 'hidden' });
        await admin.screenshot({ path: path.join(root, 'admin-response-list-mobile.png'), fullPage: true });
        assert.equal(await admin.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'Response list must fit mobile viewport.');
        await admin.setViewportSize({ width: 1440, height: 1000 });
        const downloadEvent = admin.waitForEvent('download');
        await admin.getByRole('button', { name: 'Ekspor Excel sesuai filter', exact: true }).click();
        const download = await downloadEvent;
        assert.match(download.suggestedFilename(), /^respons-formulir-.*\.xlsx$/);
        await download.saveAs(path.join(root, 'responses.xlsx'));
        await admin.getByRole('button', { name: 'Email massal', exact: true }).click();
        const deadline = new Date(Date.now() + 10 * 86400000).toISOString().slice(0, 16);
        await admin.getByLabel('Tenggat portofolio', { exact: true }).fill(deadline);
        await admin.getByLabel('Tenggat tes teknis', { exact: true }).fill(deadline);
        await admin.getByRole('button', { name: 'Pratinjau semua penerima sesuai filter', exact: true }).click();
        await admin.getByRole('heading', { name: 'Konfirmasi 1 respons', exact: true }).waitFor();
        await admin.screenshot({ path: path.join(root, 'admin-bulk-preview.png'), fullPage: true });
        await admin.setViewportSize({ width: 390, height: 844 });
        await admin.evaluate(() => window.Alpine.store('sidebar').close());
        await admin.locator('.fi-sidebar-close-overlay').waitFor({ state: 'hidden' });
        await admin.screenshot({ path: path.join(root, 'admin-bulk-mobile.png'), fullPage: true });
        assert.equal(await admin.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'Bulk preview must fit mobile viewport.');
        await admin.setViewportSize({ width: 1440, height: 1000 });
        await admin.getByLabel('Saya menyetujui pembuatan/penghubungan akun', { exact: false }).check();
        await admin.getByRole('button', { name: 'Hubungkan & kirim email massal', exact: true }).click();
        await admin.getByText('1 respons dimasukkan ke antrean', { exact: false }).waitFor();
        await admin.getByRole('button', { name: 'Periksa respons', exact: true }).click();
        await admin.getByRole('heading', { name: 'Ringkasan jawaban', exact: true }).first().waitFor();
        await admin.evaluate(() => window.scrollTo(0, 0));
        await admin.screenshot({ path: path.join(root, 'admin-response.png'), fullPage: true });
        await admin.setViewportSize({ width: 390, height: 844 });
        await admin.evaluate(() => window.Alpine.store('sidebar').close());
        await admin.locator('.fi-sidebar-close-overlay').waitFor({ state: 'hidden' });
        await admin.screenshot({ path: path.join(root, 'admin-response-mobile.png'), fullPage: true });
        assert.equal(await admin.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'Candidate answer detail must fit mobile viewport.');
        await admin.setViewportSize({ width: 1440, height: 1000 });
        await admin.getByRole('button', { name: 'Buat formulir', exact: true }).click();
        await admin.getByLabel('Judul formulir', { exact: true }).fill('Formulir browser baru');
        await admin.getByRole('button', { name: '+ Tambah field / bagian', exact: true }).click();
        await admin.getByLabel('Label pertanyaan', { exact: true }).fill('Pengalaman terakhir');
        await admin.getByRole('button', { name: 'Simpan draf', exact: true }).click();
        await admin.getByText('Draf tersimpan.', { exact: false }).waitFor();
        await admin.getByRole('button', { name: 'Pratinjau', exact: true }).click();
        await admin.getByText('Pratinjau · Tidak menyimpan jawaban', { exact: true }).waitFor();
        await admin.screenshot({ path: path.join(root, 'admin-editor.png'), fullPage: true });
        await admin.setViewportSize({ width: 390, height: 844 });
        await admin.screenshot({ path: path.join(root, 'admin-editor-mobile.png'), fullPage: true });
        assert.equal(await admin.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'Admin editor must fit mobile viewport.');
        assert.deepEqual(errors, []);
        console.log('Public forms, Excel download, bulk email preview/queue, HR review, builder and mobile layouts passed.');
    } finally { await browser.close(); }
})().catch(error => { console.error(error.message); process.exitCode = 1; });
