<x-filament-panels::page>
<div class="portal-admin candidate-form-admin">
    <div class="heading"><div><div class="eyebrow">Workspace HR · Formulir publik</div><h1>{{ $tab === 'responses' ? 'Kelola respons kandidat' : 'Formulir kandidat' }}</h1><p class="muted">Susun pertanyaan, bagikan tautan, lalu hubungkan respons ke kandidat.</p></div><button class="button primary" wire:click="create">Buat formulir</button></div>
    <nav class="form-actions" aria-label="Bagian formulir"><button class="button {{ $tab === 'forms' ? 'primary' : '' }}" wire:click="navigate('forms')">Formulir</button><button class="button {{ $tab === 'intakes' ? 'primary' : '' }}" wire:click="navigate('intakes')">Tautan penerimaan</button><button class="button {{ $tab === 'responses' ? 'primary' : '' }}" wire:click="navigate('responses')">Respons masuk</button></nav>
    <x-errors />@if($feedback)<div class="success" role="status">{{ $feedback }}</div>@endif<div wire:loading.delay role="status" class="notice">Memproses perubahan…</div>
@if($archiveId)<div class="notice"><p>Arsipkan formulir? Semua tautannya berhenti menerima perubahan. Respons dan dokumen tetap tersimpan.</p><div class="form-actions"><button class="button danger" wire:click="archive({{ $archiveId }})">Ya, arsipkan</button><button class="button" wire:click="cancelArchive">Batal</button></div></div>@endif
    @if($tab === 'forms')
        <section class="panel"><h2>Template formulir</h2><div class="table-wrap"><table class="portal-table"><thead><tr><th>Formulir</th><th>Status</th><th>Versi</th><th>Tindakan</th></tr></thead><tbody>@forelse($templates as $template)<tr><td><strong>{{ $template->title }}</strong><small>{{ count($template->fields) }} pertanyaan/bagian</small></td><td>{{ $template->archived_at ? 'Diarsipkan' : ($template->versions_count ? 'Dipublikasikan' : 'Draf') }}</td><td>{{ $template->versions_count }}</td><td><div class="form-actions">@if(!$template->archived_at)<button class="button small" wire:click="edit({{ $template->id }})">Edit draf</button><button class="button small danger" wire:click="confirmArchive({{ $template->id }})">Arsipkan</button>@endif<button class="button small" wire:click="duplicate({{ $template->id }})">Duplikasi</button></div></td></tr>@empty<tr><td colspan="4">Belum ada formulir. Buat template pertama untuk mulai mengumpulkan data kandidat.</td></tr>@endforelse</tbody></table></div>{{ $templates->links() }}</section>
    @elseif($tab === 'editor')
        <section class="panel"><div class="row"><h2>{{ $formId ? 'Edit draf formulir' : 'Formulir baru' }}</h2><span class="badge">{{ count($fields) }}/100 field</span></div><p class="muted">Nama lengkap, email terverifikasi, dan persetujuan pemrosesan data selalu tersedia. Publikasi baru tidak mengubah tautan atau jawaban lama.</p><label class="field">Judul formulir<input wire:model="formTitle" maxlength="255"></label><label class="field">Deskripsi & petunjuk<textarea wire:model="description" maxlength="5000"></textarea></label></section>
        @foreach($fields as $index => $field)
            <section class="panel form-editor-field" wire:key="field-{{ $field['id'] }}"><div class="row"><span class="eyebrow">Field {{ $index + 1 }}</span><div class="form-actions"><button class="button small" wire:click="moveField({{ $index }}, -1)" @disabled($index === 0) aria-label="Pindah ke atas">↑</button><button class="button small" wire:click="moveField({{ $index }}, 1)" @disabled($index === count($fields)-1) aria-label="Pindah ke bawah">↓</button><button class="button small" wire:click="duplicateField({{ $index }})">Duplikasi</button><button class="button small danger" wire:click="removeField({{ $index }})">Hapus</button></div></div>
            <div class="two-col"><label class="field">Label pertanyaan<input wire:model="fields.{{ $index }}.label" maxlength="255"></label><label class="field">Jenis input<select wire:model.live="fields.{{ $index }}.type">@foreach(App\Services\CandidateFormService::TYPES as $type=>$label)<option value="{{ $type }}">{{ $label }}</option>@endforeach</select></label></div><label class="field">Teks bantuan<input wire:model="fields.{{ $index }}.help" maxlength="1000"></label>
            @if($field['type'] !== 'section')<label class="form-check"><input type="checkbox" wire:model="fields.{{ $index }}.required"> Wajib diisi</label>@endif
            @if(in_array($field['type'], ['radio','select','checkbox']))<label class="field">Pilihan — satu opsi per baris<textarea wire:model="fields.{{ $index }}.options_text" placeholder="SMA/SMK&#10;Diploma&#10;Sarjana"></textarea></label>@endif
            @if(in_array($field['type'], ['text','textarea','phone','url','email']))<div class="two-col"><label class="field">Placeholder<input wire:model="fields.{{ $index }}.placeholder"></label><label class="field">Maksimum karakter<input type="number" min="1" max="10000" wire:model="fields.{{ $index }}.max_length"></label></div>@endif
            @if(in_array($field['type'], ['number','date','checkbox']))<div class="two-col"><label class="field">Minimum (opsional)<input type="{{ $field['type'] === 'date' ? 'date' : 'number' }}" step="any" wire:model="fields.{{ $index }}.min"></label><label class="field">Maksimum (opsional)<input type="{{ $field['type'] === 'date' ? 'date' : 'number' }}" step="any" wire:model="fields.{{ $index }}.max"></label></div>@endif
            @if($field['type'] === 'file')<div class="two-col"><label class="field">Maksimum MB/file<input type="number" min="1" max="{{ config('candidate_forms.max_mb') }}" wire:model="fields.{{ $index }}.max_mb"></label><label class="field">Maksimum jumlah file<input type="number" min="1" max="{{ config('candidate_forms.max_files') }}" wire:model="fields.{{ $index }}.max_files"></label></div><div class="form-choices">@foreach(config('candidate_forms.extensions') as $extension)<label><input type="checkbox" wire:model="fields.{{ $index }}.extensions" value="{{ $extension }}"> {{ strtoupper($extension) }}</label>@endforeach</div>@endif
            </section>
        @endforeach
        <div class="panel form-actions"><button class="button" wire:click="addField">+ Tambah field / bagian</button><button class="button" wire:click="save" wire:loading.attr="disabled">Simpan draf</button><button class="button" wire:click="showPreview">Pratinjau</button><button class="button primary" wire:click="publish" wire:loading.attr="disabled">Simpan & terbitkan versi</button></div>
        @if($preview)<section class="panel"><span class="badge">Pratinjau · Tidak menyimpan jawaban</span><h1>{{ $formTitle }}</h1><p>{{ $description }}</p><label class="field">Nama lengkap *<input disabled placeholder="Nama kandidat"></label><label class="field">Email utama *<input disabled placeholder="kandidat@email.com"></label>@include('forms.fields', ['fields'=>$previewFields,'answers'=>[],'disabled'=>true])<p>Persetujuan pemrosesan data wajib sebelum kirim final.</p></section>@endif
    @elseif($tab === 'intakes')
        <form wire:submit="createIntake" class="panel"><h2>Buat tautan penerimaan</h2><p class="muted">Setiap tautan terikat ke satu versi, posisi, dan periode. Zona waktu: {{ App\Models\AppSetting::valueFor('timezone') }}.</p><div class="two-col"><label class="field">Versi formulir<select wire:model="intake.candidate_form_version_id" required><option value="">Pilih versi terbit</option>@foreach($versions as $version)<option value="{{ $version->id }}">{{ $version->title }} · v{{ $version->number }}</option>@endforeach</select></label><label class="field">Posisi<select wire:model="intake.position_id" required><option value="">Pilih posisi</option>@foreach($positions as $position)<option value="{{ $position->id }}">{{ $position->name }}</option>@endforeach</select></label><label class="field">Periode<select wire:model="intake.recruitment_period_id" required><option value="">Pilih periode</option>@foreach($periods as $period)<option value="{{ $period->id }}">{{ $period->name }}</option>@endforeach</select></label><label class="field">Maksimum respons final (opsional)<input type="number" min="1" wire:model="intake.max_responses"></label><label class="field">Mulai (opsional)<input type="datetime-local" wire:model="intake.starts_at"></label><label class="field">Tenggat (opsional)<input type="datetime-local" wire:model="intake.deadline"></label></div><div class="form-actions"><button class="button primary" wire:loading.attr="disabled">Buat tautan publik</button></div></form>
        <section class="panel"><h2>Tautan yang tersedia</h2>@forelse($intakes as $item)<div class="form-intake-row"><div class="row"><div><strong>{{ $item->version->title }} · v{{ $item->version->number }}</strong><p class="muted">{{ $item->position->name }} · {{ $item->period->name }} · {{ $item->submitted_count }} terkirim / {{ $item->responses_count }} mulai</p><small>{{ $item->open() ? 'Terbuka' : 'Ditutup / di luar jadwal' }}</small></div><button class="button small" wire:click="toggleIntake({{ $item->id }})">{{ $item->active ? 'Tutup penerimaan' : 'Aktifkan penerimaan' }}</button></div><label class="field">Tautan publik<input readonly value="{{ route('forms.show', $item->slug) }}" x-on:focus="$el.select()"></label><div class="form-actions"><a class="button small" href="{{ route('forms.show', $item->slug) }}" target="_blank" rel="noopener">Buka formulir</a><button type="button" class="button small" x-on:click="navigator.clipboard.writeText(@js(route('forms.show', $item->slug))).then(() => $el.textContent = 'Tersalin').catch(() => $el.textContent = 'Salin dari kolom tautan')">Salin tautan</button></div></div>@empty<p class="muted">Belum ada tautan. Terbitkan formulir, lalu pilih posisi dan periode.</p>@endforelse{{ $intakes->links() }}</section>
    @elseif($tab === 'responses')
        @include('filament.pages.partials.form-responses')
    @endif
</div>
</x-filament-panels::page>
